# Build settings

port: 4000
markdown:  kramdown
permalink: /:title
plugins:   [jekyll-sitemap, jekyll-feed,  jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)

title:		   "Rebecca S. Zhang"
description: "Portfolio of Rebecca S. Zhang"
author:      "Rebecca S. Zhang"
url: "https://rebbszhang.com"
